Default: &defaults
  database: windroosstart.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: windroosstart_test.sqlite3
  <<: *defaults

Staging:
  database: windroosstart_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: windroosstart_production.sqlite3
  poolsize: 100
  <<: *defaults
